dataset:
  test_split: 0.05
  train_split: 0.8
  val_split: 0.15
model:
  confidence_threshold: 0.3
  input_size: 640
  iou_threshold: 0.45
  max_detections: 300
  name: yolov8n
training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.01
  patience: 50
  save_period: 10
